### PR TITLE
ZergMacroTracker: Look for UpdateTargetAbilityEvent to track injects.

### PR DESCRIPTION
**Pull request by gravelweb**
Fixes ggtracker/ggtrackerstack#49 once https://github.com/ggtracker/sc2reader/pull/14 changes are pushed as well.

### CODE REVIEW

**Comment by dsjoerg** [comment]
This is very cool!

Do tests pass?
Can you add a new test that breaks without this change?

**Comment by dsjoerg** [comment]
Hey @gravelweb , can you let me know if tests pass on this one?
And ideally add a new test that breaks without this change?

It looks simple enough a change but hard experience has taught me to mistrust appearances.

**Comment by gravelweb** [comment]
Let's find out :) I added a unit tests. It's technically incorrect, because of some of the open issues, but this test can now be used for TDD of ggtracker/ggtrackerstack#50!

**Comment by gravelweb** [comment]
Hey @dsjoerg. It looks like the test environment is not configured properly:

<pre>
cd /home/ubuntu/ggpyjobs && { echo 'import json;from django.conf import settings;print('\''OUT: '\'' + settings.TEST_RUNNER)' | python manage.py shell; }
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    import settings
  File "/home/ubuntu/ggpyjobs/settings.py", line 20, in <module>
    with open(PROJECT_PATH + '/config/database.yml','r') as db_yaml:
IOError: [Errno 2] No such file or directory: '/home/ubuntu/ggpyjobs/config/database.yml'
((and (cd "/home/ubuntu/ggpyjobs") (group (pipe (echo "'import json;from django.conf import settings;print('\\''OUT: '\\'' + settings.TEST_RUNNER)'") (python manage.py shell))))) returned exit code 1
</pre>

**Comment by dsjoerg** [comment]
I don't care about CI at this moment, but do the tests at least pass in your environment?

**Comment by gravelweb** [comment]
Yes they do, except for one about uploading to aws and reading it back. I'm guessing I don't have my test buckets set up properly.

The error is relating to a missing attribute on a map.. don't have PC to copy stack trace right now.

**Comment by gravelweb** [comment]
<pre>
======================================================================
ERROR: test_map_stuff (sc2parse.tests.SC2ReaderToEsdbTestCase)
Parsing map info, storing in DB, retrieving from battle.net, storing in S3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/esdb/vendor/ggpyjobs/sc2parse/tests.py", line 132, in test_map_stuff
    self.assertEquals(matchDB.map.name, 'Molten Crater')
AttributeError: 'NoneType' object has no attribute 'name'
----------------------------------------------------------------------
Ran 29 tests in 55.418s
FAILED (errors=1)
</pre>

**Comment by gravelweb** [comment]
I should add that this test was failing before I included any of my changes (including sc2reader changes)

**Pull request merged**
