### PR TITLE
update to sc2reader RC merging graylinkim/sc2reader

### PR DESCRIPTION
**Pull request by StoicLoofah**
Followup to https://github.com/ggtracker/sc2reader/pull/16

Sorry about the newline stuff. It's all in my editor settings.

I got the following result after cleaning all of this up:

```
(ggpyjobs)kevin@chowmein:~/ggpyjobs$ GGFACTORY_CACHE_DIR=testcache GGPYJOBS_CONFIG_PATH=config DJANGO_SECRETKEY=foo ./manage.py test sc2parse
LOTS OF OTHER STUFF: I actually have a ton of unknown/missing messages in here
======================================================================
ERROR: test_map_stuff (sc2parse.tests.SC2ReaderToEsdbTestCase)
Parsing map info, storing in DB, retrieving from battle.net, storing in S3
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kevin/ggpyjobs/sc2parse/tests.py", line 132, in test_map_stuff
    self.assertEquals(matchDB.map.name, 'Molten Crater')
AttributeError: 'NoneType' object has no attribute 'name'

----------------------------------------------------------------------
Ran 37 tests in 65.028s

FAILED (errors=1)
Destroying test database for alias 'default'...
```

so the tests almost all pass. i'm hoping that one error is because i didn't actually go through all of the setup steps around configuring the DB and AWS and such. Do you mind giving this branch a shot in your correctly configured environment?

### CODE REVIEW

**Comment by dsjoerg** [comment]
Sadly I get the exact same error in my test env.

**Comment by dsjoerg** [comment]
But, it's incredible that all the other tests pass!  Great work!

**Comment by StoicLoofah** [comment]
dang. okay, i'll work on it. thanks for checking!

**Comment by StoicLoofah** [comment]
Okay, I might have not doing things right, but in my environment, I reverted to `ggpyjobs/master` and `ggtracker/sc2reader/upstream`, cleared my caches, and ran this test, and it still failed. As such, I'm not certain whether the failure is linked to the changes I made. Do you see the same thing in your setup?

**Comment by dsjoerg** [comment]
I think you have a configuration problem where it's still running the wrong code.  On my laptop, I confirmed that all the tests passed before running your code.  Then I switched to your code and got the one failure.  And now I've switched back to ggpyjobs/master and ggtracker/sc2reader/upstream and the test passes.

I've definitely had problems in the past with my setup running a different version of a library than what I intended, I find Python path configuration to be an error-prone pain in the butt.

`pip install -r requirements.txt` of course, and this might also help you figure out what's going on:

```
was:ggpyjobs david$ PYTHONPATH=src/sc2reader python
PYTHONPATH=src/sc2reader python
Python 2.7.9 (default, Apr  7 2015, 07:58:25) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sc2reader
import sc2reader
>>> sc2reader.__file__
sc2reader.__file__
'/Users/david/Dropbox/Programming/ggpyjobs/src/sc2reader/sc2reader/__init__.pyc'
```

**Comment by StoicLoofah** [comment]
Thanks. Should be fixed now. I didn't set the permissions on S3 properly, so it was failing in all cases. After that, I found 1 more instance of `replay.gateway` -> `replay.region` and updated that, and the test is passing for me now. Do you see the same thing from your side?

**Comment by dsjoerg** [comment]
Tests pass!  Working on it now

**Comment by dsjoerg** [comment]
OK I heroically threw this into production and the two replays I tried to process worked fine. :)

**Comment by dsjoerg** [comment]
Thanks for all your work on this!

**Comment by EHadoux** [comment]
Wow, that's incredible guys. Well done. 
Does it mean that the new official repository is this one and that any additional plugin should be PR here?
EDIT: sorry I meant ggtracker/sc2reader for the official repo but still here for the plugins.

**Comment by dsjoerg** [comment]
Yes, https://github.com/ggtracker/sc2reader is official and any PR should go there.  Know any good maintainers?  :)  I'm not really looking for that job

**Comment by EHadoux** [comment]
To be really honest, apart from Kevin and yourself (and far far behind maybe me) I am not sure a lot of people will actually submit pull requests unfortunately.

**Comment by StoicLoofah** [comment]
i think keeping the library patched with new SC2Replay file versions is sufficient for maintaining the project. I'm happy to contribute those changes to this repo from here on out. Admittedly, though, I have usually been slower to do that than @dsjoerg in the past, but I'll try!

**Pull request merged**
