### PR TITLE
fix LotV time scaling

### PR DESCRIPTION
**Pull request by dmpaul26**
EDIT: Looking through the code still, this probably doesn't fix the problem, it's in the sc2reader used being out of date for LotV. Which version is used here and how do we implement changes to it?

### CODE REVIEW

**Comment by dsjoerg** [comment]
Hi, we use the "upstream" branch of https://github.com/ggtracker/sc2reader

(You can verify that from https://github.com/dsjoerg/ggpyjobs/blob/master/requirements.txt by seeing that it refers to the next-to-last commit in https://github.com/ggtracker/sc2reader/commits/upstream)

I agree that this commit alone does not fix the problem and would probably introduce a bunch of bugs if it went into production.  Do you agree?

**Comment by dsjoerg** [comment]
Anyway @dmpaul26 thanks for looking at this.  I agree with your strategy of starting with sc2reader and getting it to work correctly.  Once sc2reader works correctly we can strategize about the steps for making ggtracker correct.

**Comment by dmpaul26** [comment]
I sent you a couple messages on reddit, that's how I originally contacted you. You can basically ignore almost everything written as I've figured out most of it. What I said basically agreed with this. I dove in way deeper than I realized. I 100% agree what I tried to do here was a bad idea. I'm going to continue looking through, and getting a better idea of what's going on before I try to commit anything further.

**Comment by dmpaul26** [comment]
It seems the best fix would be based on how Blizzard implemented the game speed change. I searched, but couldn't find much more than they wanted to be careful how the implemented it.

My understanding of the code is this:

```
self.game_length = utils.Length(seconds=self.frames/16)
self.length = self.real_length = utils.Length(seconds=int(self.frames/self.game_fps))
```

These lines are equivalent because of

`self.game_fps = 16.0`

in the Replay constructor.

While, in Replay.load_details()

```
self.game_length = self.length
self.real_length = utils.Length(seconds=int(self.length.seconds/GAME_SPEED_FACTOR[self.speed]))
```

real_length ends up being the correct value for LotV, since game time is 1:1 with real time (note below), so one way to fix it could be to make all three, real_length, game_length and length equivalent if the replay's expansion is LotV.

Thoughts?

Note: I tested these values using the GUI-based program I mentioned earlier, and a couple replays from either expansion. I modified it to work almost as a testing platform for sc2reader.

**Comment by dsjoerg** [comment]
Hi, I want to help, but I'm not sure what state our conversation is in now.  One way to proceed is for you to identify one single thing that seems wrong in the front end / web site, and I can show you the path of code from the front to the back that causes that number to be wrong.

I suggest this because I think there are a bunch of places in the code that will need to be adjusted, but rather than get overwhelmed by the size of the task, maybe the way forward is to pick one thing and fix it, and repeat.

**Comment by dmpaul26** [comment]
I agree with you. I keep trying to bite off more than I know how to chew. The one thing I'll focus on is the time difference in HotS and LotV. On the front end, looking at the match screen, in the top left it displays the map, expansion, how long ago the match was played and duration. For LotV replays, the duration shows the actual duration \* 1.4. The duration is a reference to

`@match.duration_minutes`

Which (if I traced this correctly) is set by [this](https://github.com/dsjoerg/ggpyjobs/blob/master/sc2parse/sc2reader_to_esdb.py#L640) or [this](https://github.com/dsjoerg/ggpyjobs/blob/master/sc2parse/sc2reader_to_esdb.py#L1190)

Every chart on the match screen shows the same time. I'm not too familiar with web development, so it's a bit more difficult to trace that part for me. I assumed the length was just being pulled from the DB and was already incorrect in the DB.

**Comment by dsjoerg** [comment]
The critical path is this:

https://github.com/dsjoerg/ggpyjobs/blob/master/sc2parse/sc2reader_to_esdb.py#L867

then in the gg repository, gg/lib/esdb/match.rb:38
    def duration_minutes
      return (duration_seconds / 60.0).round
    end

then in the ggtracker web repo,
ggtracker/app/views/matches/show.html.erb:14 @match.duration_minutes

**Comment by dmpaul26** [comment]
Right, so at 

https://github.com/dsjoerg/ggpyjobs/blob/master/sc2parse/sc2reader_to_esdb.py#L867

duration_seconds is set by replay.length. replay.length comes from sc2reader's Replay class and is set at

https://github.com/ggtracker/sc2reader/blob/upstream/sc2reader/resources.py#L256

Comparing the value of replay.length to an actual replay shows that replay.length/1.4 gives the correct length of a match in LotV.

1.4 was the modifier for the "faster" speed setting in HotS, which is now 1 in LotV according to Blizzard

I didn't find anywhere replay.length actually gets multiplied by 1.4, so after checking which expansion the replay was played in, dividing the length by the game speed factor constant

https://github.com/ggtracker/sc2reader/blob/upstream/sc2reader/constants.py#L67

would return the correct length for the "faster" game speed setting. I haven't tested it against the other game speeds and I'm not sure how Blizzard adjusted the others, they only mentioned "faster".

**Comment by dsjoerg** [comment]
Make sense.  For the change proposed in this pull request, rather than making the change in master, can you do it in a branch or keep it in your own fork for now?

I'm asking because until the changes are complete, the system as a whole will be in a weird inconsistent state.  For example with this change alone, the web page will say that the match is 10 minutes, but the slider on that same page will say it is 14 minutes.

Also, this change may cause some other piece of code to crash.

But I agree that this change is a step in the right direction.  By keeping the changes isolated on a separate branch we can work through the issues one at a time until the whole system looks good & works properly.

**Comment by dmpaul26** [comment]
The change I proposed in this commit is different than what we're talking about now. I think the change in that commit would cause problems all over the place. This change would be in 

https://github.com/ggtracker/sc2reader/blob/upstream/sc2reader/resources.py

right? The change is for sc2reader.

I agree with keeping them separate until all working properly. Is there a way for me to test what my changes would reflect on the web page, without obviously using the live version?

**Comment by dsjoerg** [comment]
To test what the web page would show, you'd set up a development version of the web site.  What people have done in the past is start with the README instructions at https://github.com/dsjoerg/ggtracker and take it from there.  But if you're new to web development you might find it challenging.  Then again maybe it'll be smooth sailing.

Are you familiar with Docker?  If so then maybe it's time for me to set up a Docker container that can run this stuff.

**Comment by dmpaul26** [comment]
I'm not familiar with Docker. I'll take a shot at going through the README, and setting up a development version, if I can't seem to figure it out I'll take a look at Docker too. Would there be a better place to contact you rather than just commenting back and forth on this PR? Not that I have a problem with it, if it works for you, works for me. Just curious.

**Comment by dsjoerg** [comment]
This is good :) future generations can learn from it.   dsjoerg at ggtracker dot com also works.

**Comment by nickelsen** [comment]
@dmpaul26 If you would have a look at ggtracker/sc2reader#10, I'd really appreciate it. I think it is in line with what you're talking about here, but I might be overcomplicating things.

**Comment by dsjoerg** [comment]
By the way @dmpaul26, https://github.com/ggtracker/ggtrackerstack is a fully functioning environment for building your own ggtracker dev env.  I just followed the README and it works great.

**Comment by dsjoerg** [comment]
This PR is no longer necessary, ggtracker/sc2reader#10 addresses the problem by directly changing replay.length.seconds which `matchDB.duration_seconds` is set from.

**Pull request closed without merging**
